### PR TITLE
Full rewrite of browser extension

### LINKED ISSUE #49: Multiple textareas
OMG, this is sooo cool. I love this extension/sublime package.

Is there any way to have this work in codepen on all the textareas eg. HTML, CSS, JS?

P.S. Don't sell this to codepen :)

### LINKED ISSUE #75: Doesn't work on fields inside iframes
GhostText for Chrome doesn't recognize textarea elements shown in the result pane of JSFiddle pages.  For example, I've made this very simple JSFiddle that contains HTML which makes a form with a textarea element, no JavaScript, and no CSS:

https://jsfiddle.net/lsloan/1a2nywf0/

Even when the textarea element in the results pane already has focus, activating GhostText on that page shows the message:

> There are multiple text areas on this page.  Click on the one you want to use.

GT only acknowledges clicks on the textarea elements associated with the other panes for HTML, JavaScript, or CSS.  Nothing happens when the textarea element in the result pane is clicked.

A similar thing happens when viewing the embedded version of this JSFiddle, showing only the result tab:

https://jsfiddle.net/lsloan/1a2nywf0/embedded/result/

Whether the textarea element has focus, activating GT shows this message (in red):

> No text area elements on this page

I have several extensions installed in Chrome.  However, I successfully reproduced the same problem in a new profile that had only the GT extension installed.

I'm using:
- Google Chrome Version 51.0.2704.84 (64-bit)
- GhostText for Chrome 1.1.4
- "Ghost Text for VIm" - https://github.com/falstro/ghost-text-vim
  - Which required an upgrade to Tcl/Tk 8.6.4, installed using homebrew
- MacVim Custom Version 7.4 (81)

Note that the interface with Vim works well enough and doesn't seem to be the problem in this case.  I've been successful in getting GT to open Vim documents with the contents of textarea elements on other web pages.

### LINKED ISSUE #85: Notifications should not be queued
Notifications that happen close together pile up and make no sense. This probably requires a rewrite of the notifications code, possibly integrating https://github.com/Cacodaimon/GhostText-for-Chrome/issues/24

### LINKED ISSUE #95: Multiple windows and tabs
### 1. Summary

When I work use GhostText, many windows open for me.

### 2. Expected behavior

Only one new window open, when I use GhostText.

### 3. Actual behavior

Multiple windows:

Multiple windows

### 4. Settings

My `User/GhostText.sublime-settings`:

```json
{
    "new_window_on_connect": true
}
```

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I click to Ghost button in Firefox → I select textarea element → one new Sublime Text window and one tab in current Sublime Text window open for me.

If I click to Ghost button in Firefox again 2 times and select textarea element again, 3 new windows and one new tab in current window open for me.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**Firefox:**
51.0.1 (64-bit)
**GhostText for Firefox:**
1.2.4.1
**GhostText for Sublime Text:**
1.0.13

Thanks.

### LINKED ISSUE #114: Opens multiple editor windows on subsequent clicks
I'm using GhostText 17.10.25.1400 with Firefox 57 on Ubuntu 17.04 together with <https://github.com/falstro/ghost-text-vim>

When I first click on the GhostText icon, it opens one gvim window. When I save the text and close the editor, and then click on the GhostText icon a second time, it opens two gvim windows, one empty, one with the text from that text area that is in focus. Each time I repeat this, I get one more empty gvim window (so on the 5th run I get 4 empty and 1 normal gvim windows).

There is an issue in the vim plugin repo at falstro/ghost-text-vim#3 which claims this is a problem in GhostText, not in the vim plugin.

### LINKED ISSUE #145: GhostText stopped working in Firefox 63
# Setup

Browser: Firefox 63.0 (64-bit)
Editor: Sublime Text 3.1.1 (Build 3176)

# Description

After upgrading from Firefox 62 to Firefox 63, GhostText stopped working.  It still works when using Chromium 70.  In the console, I can see the following output in Firefox:

    Got message: {action: "select-field", tabId: 32}        → ​content.js:39:9
    GhostText: selectField()                                → content.js:150:9
    GhostText: detector.focusEvent()                        → content.js:154:13
    GhostText: reportFieldData()                            → content.js:206:9

The field is highlighted (blue GhostText frame) but nothing else happens.

Any ideas what might be the issue here?  What kind of logs/debugging can I contribute to narrow the issue down?

### PR DESCRIPTION
**Pull request by fregante**
This adds a few features and fixes several long-standing bugs

Missing:

- [x] Show user notifications
- [x] Support more than textareas

Closes #49 
Closes #75
Fixes #85
Fixes #95
Fixes #114
Fixes #145

### CODE REVIEW

**Comment by bfred-it** [comment]
Blocked because this doesn't work on HTTPS sites because of _mixed content_ limitations. I'll have to adjust it again.

**Comment by bfred-it** [comment]
Pinging some recent users to try this out before I release it into the wild. It should fix a few long-standing issues without hopefully breaking other situations.

I've been testing it in the demo in Firefox and Chrome (+ Sublime Text): https://ghosttext.github.io/GhostText/demo/

Let me know if it works for you and if you're using any non-Sublime plugins.

**Comment by ilpssun** [comment]
As commented in #145, the new plugin version does not work for me.  Give me a hint what kind of logs or tests I should provide you with to help you with development.  I am currently at a loss where to dig deeper as the logs I can see (FF + ST console) do not output any errors that I can associate with GhostText.

**Comment by bfred-it** [comment]
It turns out that the CSP issue did not disappear but, again, I had only run my Firefox tests on the local (http) demo while testing Chrome everywhere.

So yes even after my recent re-work I'll have to kind of re-think it to overcome that Firefox security issue

**Comment by subnut** [comment]
@fregante Would you please tell me how I can obtain and install this version of the plugin? I am on firefox.

**Comment by fregante** [comment]
This is finally merged! Please help me test it in https://github.com/GhostText/GhostText/issues/172

**Pull request merged**
